version: '3'

services:
  influxdb:
    container_name: influxdb
    image: influxdb
    networks:
      - concourse_default
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    container_name: grafana
    build: ./grafana
    networks:
      - concourse_default
    ports:
      - 3000:3000

networks:
  concourse_default:
 
volumes:
  influxdb-data:
