{
 "title": "Worker metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "description": "Shows the per-ATC number of error status codes returned in the responses.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "measurement": "http response time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "500" }
     ]
    }
   ]
  },
  {
   "title": "Per-worker state",
   "type": "graph",
   "description": "Represents the workers' state over time.\n\nEach value in the Y-axis represents a given state as follows:\n\n1. Stalled\n2. Retiring\n3. Landed\n4. Landing\n5. Running\n\nFor more information about what each state means, check out [worker internals](https://concourse-ci.org/worker-internals.html#worker-lifecycle).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "state" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error logs count",
   "type": "graph",
   "description": "Count of errors reported through `log.Error` messages in ATC code.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_message",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "message" ], "type": "tag" }
     ],
     "measurement": "error-messages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker States",
   "type": "graph",
   "description": "Aggregate state of workers over time.\n\nFor more information about what each state means, check out [worker internals](https://concourse-ci.org/worker-internals.html#worker-lifecycle).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_worker_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "worker_state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "worker_state", "operator": "=", "value": "stalled" }
     ]
    },
    {
     "alias": "$tag_worker_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "worker_state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "worker_state", "operator": "=", "value": "retiring" }
     ]
    },
    {
     "alias": "$tag_worker_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "worker_state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "worker_state", "operator": "=", "value": "landed" }
     ]
    },
    {
     "alias": "$tag_worker_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "worker_state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "worker_state", "operator": "=", "value": "landing" }
     ]
    },
    {
     "alias": "$tag_worker_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "worker_state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "worker_state", "operator": "=", "value": "running" }
     ]
    }
   ]
  }
 ]
}