{
 "title": "Overall2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG values FROM cpu WITH key=host"
   },
   {
    "name": "netif",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$host/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\" WHERE host =~ /$host/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "For how long the system has been running.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "description": "How many CPUs the machine has",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory utilization",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "softirq" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Saturation (load)",
     "type": "graph",
     "description": "Current system load, i.e. the number of processes using CPU or waiting for system resources (usually CPU and disk).\n\nNote that it *doesn't* distinguish between CPU and DISK load.",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5m" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "15m" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - $disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_device",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_name",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "available" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Saturation (page faults /s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "kernel_vmstat",
       "select": [
        [
         { "params": [ "pgfault" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" },
         { "params": [ "minor" ], "type": "alias" }
        ],
        [
         { "params": [ "pgmajfault" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" },
         { "params": [ "major" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interface - $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col - $tag_interface",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "rx" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "rx" ], "type": "alias" }
        ],
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
       ]
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "rx" ], "type": "alias" }
        ],
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "tx" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}